name: Check for New Sends

on:
  workflow_dispatch:
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:      
      contents: write   
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Sync with remote repository
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git pull --rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- NEW STEP: Cache Python packages to speed up installation ---
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip # The directory to cache
          # Create a unique key for the cache based on the OS, Python version, and requirements file hash.
          # If requirements.txt changes, this key will change, and a new cache will be created.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # --- MODIFIED STEP: Now installs dependencies much faster ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python scraper.py

      - name: Update run timestamp
        run: date > last_run.txt
          
      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update state and run timestamp"
          file_pattern: "last_sends.json last_run.txt" 
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"