name: Check for New Sends

on:
  workflow_dispatch:
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:      
      contents: write   
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python scraper.py

      # --- NEW STEP ---
      # This step creates a new file or updates an existing one with the current timestamp.
      # This guarantees that there is always a file change for the next step to commit.
      - name: Update run timestamp
        run: date > last_run.txt

       - name: Sync with remote repository
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git pull --rebase
          
      # --- MODIFIED STEP ---
      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update state and run timestamp"
          file_pattern: "last_sends.json last_run.txt" 
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"

  